---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/protitude/dotfiles
dotfiles_repo_local_destination: ~/Documents/dotfiles
dotfiles_repo_accept_hostkey: true
dotfiles_files:
  - .bash_profile
  - .gitconfig
  - .gitignore
  - .goto_shortcuts
  - .osx
  - .tmux-git
  - .tmux.conf
  - .tmux-git.conf
  - .vim
  - .vimrc
  - .zshrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - awscli
  - bash-completion
  - colordiff
  - cowsay
  - doxygen
  - fortune
  - gettext
  - gflags
  - gh
  - gifsicle
  - git
  - github/gh/gh
  - go
  - gpg
  - guetzli
  - hh
  - htop
  - httpie
  - hub
  - hugo
  - iperf
  - jq
  - libdvdcss
  - libevent
  - libpng
  - mas
  - mcrypt
  - nmap
  - node
  - npm
  - nvm
  - nvm
  - openssl
  - p7zip
  - packer
  - php@7.4
  - pv
  - python
  - readline
  - s3cmd
  - selenium-server-standalone
  - sqlite
  - sqlite
  - ssh-copy-id
  - subversion
  - tmux
  - tree
  - webp
  - wget
  - wrk
  - wrk
  - zsh-history-substring-search

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - adobe-creative-cloud
  - android-platform-tools
  - docker
  - android-file-transfer
  - caffeine
  - calibre
  - chromedriver
  - cyberduck
  - google-chrome
  - font-hack-nerd-font
  - gpg-suite
  - dropbox
  - firefox
  - handbrake
  - kindle
  - insync
  - iterm2
  - lando
  - licecap
  - macvim
  - nvalt
  - screenflow
  - sequel-ace
  - skype
  - skitch
  - slack
  - sublime-text
  - thunderbird
  - tower
  - transmit
  - unetbootin
  - vagrant
  - vagrant-manager
  - visual-studio-code
  - vlc
  - webpquicklook

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 409183694 , name: "Keynote" }
  - { id: 405399194 , name: "Kindle" }
  - { id: 1295203466 , name: "MS Remote Desktop" }
  - { id: 1116599239, name: "Nordvpn" }
  - { id: 409203825 , name: "Numbers" }
  - { id: 409201541 , name: "Pages" }
  #- { id: 874139669, name: "Signal" }
  - { id: 1475387142, name: "TailScale" }
  - { id: 497799835, name: "Xcode" }
  - { id: 405399194 , name: "Yubikey" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks:
  - "tasks/mac-misc.yml"

